services:
  - type: web
    name: krn-mrp-plant1
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn krn_mrp_app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: KRN_ADMIN_PASSWORD
        sync: false
      - key: KRN_STORE_PASSWORD
        sync: false
      - key: KRN_MELTING_PASSWORD
        sync: false
      - key: KRN_ATOM_PASSWORD
        sync: false
      - key: KRN_RAP_PASSWORD
        sync: false
      - key: KRN_ANNEAL_PASSWORD
        sync: false
      - key: KRN_PULV_PASSWORD
        sync: false
      - key: KRN_GRIND_PASSWORD
        sync: false
      - key: KRN_FG_PASSWORD
        sync: false
      - key: KRN_QA_PASSWORD
        sync: false
      - key: KRN_VIEW_PASSWORD
        sync: false
